version: '3'
services:
  mountebank:
    container_name: 'mountebank'
    image: 'bbyars/mountebank:latest'
    restart: always
    network_mode: bridge
    volumes:
      - './imposters:/imposters'
    ports:
      - '2525:2525'
      - '8090:8090'
    command: 'restart --configfile /imposters/imposters.ejs --allowInjection'
