version: '3.1'

services:
  mongo_primary:
    image: mongo
    ports:
      - 30001:27071
    volumes:
      - $HOME/.cache/docker/vol/mongoclusterdata/mongo_primary:/data/db
    networks:
      - mongocluster
    command: mongod --replSet mongo_replica_set_name
  mongo_slave:
    image: mongo
    ports:
      - 30002:27071
    volumes:
      - $HOME/.cache/docker/vol/mongoclusterdata/mongo_slave:/data/db
    networks:
      - mongocluster
    command: mongod --replSet mongo_replica_set_name
    depends_on:
      - mongo_primary

networks:
  mongocluster:
    driver: bridge
