version: '3.6'
services:
  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=Falcon@007
      - SPLUNK_ENABLE_LISTEN=9997
    ports:
      - "8111:8000"
  splunkforwarder:
    image: splunk/universalforwarder:latest
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_FORWARD_SERVER=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=Falcon@007
      - SPLUNK_ADD=monitor /logs
    restart: always
    depends_on:
      - splunk
    volumes:
      - log_volume:/logs
    ports:
      - "8222:8089"
volumes:
  log_volume: