version: '3.1'
services:
  local-zookeeper:
    ports:
      - "2181:2181"
    image: zookeeper:latest
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=local-zookeeper:2888:3888
    volumes:
      - ./databackup/zoo1/data:/data
      - ./databackup/zoo1/datalog:/datalog
    network_mode: bridge